(define (problem starpuzzle4)
  (:domain starpuzzle)
  (:objects D1 D2 D3 D4 PA PB PC PD PA0 PB0 PC0 PD0)
  ;D1, D2, D3, D4 - Disks
  ;PA, PB, PC, PD - Posts
  ;PA0, PB0, PC0, PD0 - Base of each Post respectively
  (:init 
		(on D1 D2)
		(on D2 D3)
		(on D3 D4)
		(on D4 PA0)
		(clear D1)
		(clear PB0)
		(clear PC0)
		(clear PD0)
		(unique PD)
		(belong PA D1)
		(belong PA D2)
		(belong PA D3)
		(belong PA D4)
		(belong PA PA0)
		(belong PB PB0)
		(belong PC PC0)
		(belong PD PD0)
		(smaller D1 D2)
		(smaller D1 D3)
		(smaller D1 D4)
		(smaller D1 PA0)
		(smaller D1 PB0)
		(smaller D1 PC0)
		(smaller D1 PD0)
		(smaller D2 D3)
		(smaller D2 D4)
		(smaller D2 PA0)
		(smaller D2 PB0)
		(smaller D2 PC0)
		(smaller D2 PD0)
		(smaller D3 D4)
		(smaller D3 PA0)
		(smaller D3 PB0)
		(smaller D3 PC0)
		(smaller D3 PD0)
		(smaller D4 PA0)
		(smaller D4 PB0)
		(smaller D4 PC0)
		(smaller D4 PD0))

	(:goal 
		(and 
		(belong PC D1)
		(belong PC D2)
		(belong PC D3)
		(belong PC D4)
		(on D1 D2)
		(on D2 D3)
		(on D3 D4)
		(on D4 PC0))))
